# Generated by Django 5.0.3 on 2024-03-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'United States of America'), ('CHN', 'China'), ('JPN', 'Japan'), ('DEU', 'Germany'), ('IND', 'India'), ('GBR', 'United Kingdom'), ('FRA', 'France'), ('ITA', 'Italy'), ('BRA', 'Brazil'), ('CAN', 'Canada'), ('RUS', 'Russia'), ('KOR', 'South Korea'), ('AUS', 'Australia'), ('ESP', 'Spain'), ('MEX', 'Mexico'), ('IDN', 'Indonesia'), ('TUR', 'Turkey'), ('SAU', 'Saudi Arabia'), ('CHE', 'Switzerland'), ('NLD', 'Netherlands')], max_length=100, null=True)),
            ],
        ),
    ]
